import { AxiosError } from 'axios';
import { GenericError, AxiosErrorContext } from '../types/Error';
import { HubSpotAuthError } from '../models/HubSpotAuthError';
export declare function isSpecifiedError(err: Error | AxiosError, { statusCode, category, subCategory, }: {
    statusCode?: number;
    category?: string;
    subCategory?: string;
}): boolean;
export declare function isMissingScopeError(err: Error | AxiosError): boolean;
export declare function isGatingError(err: Error | AxiosError): boolean;
export declare function isApiUploadValidationError(err: AxiosError<any>): boolean;
export declare function isSpecifiedHubSpotAuthError(err: GenericError, { status, category, subCategory }: Partial<HubSpotAuthError>): boolean;
export declare function getAxiosErrorWithContext(error: AxiosError<any>, context?: AxiosErrorContext): Error;
/**
 * @throws
 */
export declare function throwApiError(error: AxiosError, context?: AxiosErrorContext): never;
/**
 * @throws
 */
export declare function throwApiUploadError(error: AxiosError, context?: AxiosErrorContext): never;
